### ISSUE TITLE
[Android] Missing GPS Data

### ISSUE THREAD

**Issue by tanvimurke** [onnela-lab/beiwe-android#66] opened 2023-08-01 19:53 UTC
Hi Team,

We have been using your app as a reference and have recently made some changes to ensure its compatibility with OS 12 and 13. However, we are currently encountering an issue related to the transfer of GPS files to the database.
Since we value your expertise and experience with the app, we wanted to reach out to inquire if you have faced a similar issue in the past or are aware of it and its potential resolution. Any insights or assistance you can provide would be greatly appreciated.
Looking forward to hearing from you soon.

Regards,
Tanvi Murke
Research Assistant, Carnegie Mellon University

**Comment by biblicabeebli** [comment] 2023-08-06 15:47
Is this specifically with ios 12/13, or more general? According to this chart the device would have to be strictly older than a the 6s generation. https://iosref.com/ios 

I have an iPhone 6+ that I can test ios 12 on, but working on this is a matter of time vs payout. Are you using an old device for testing, or do you have participants on old iOS versions?

There was a compatibility issue with iOS 15.7 that we were never able to track down, all non-survey data streams failed.

I will need you to do the following before I can do more:
- make sure the version of the app on the device is "Beiwe2", "Beiwe" was removed from the app store maybe 6 months ago.
- what exactly is the version of the app running? Up-to-date backend will display this on the participant page.
- I need your exported study settings json - my email is my username at gmail if you would prefer to email rather than post that here.
- iOS is heavily dependent on push notifications for app persistence. If you don't have those credentials please get in touch by email.

**Comment by tanvimurke** [comment] 2023-08-06 23:02
Hi Eli,

Thank you so much for reverting back. The issue I posted is with the
Android app.

Regards,
Tanvi Murke

**Comment by biblicabeebli** [comment] 2023-08-07 03:34
WOOPS.
Uh.
I'll update this tomorrow, my bad.

Do need that exported study info.

**Comment by tanvimurke** [comment] 2023-08-07 04:19
Hi Eli,

No problem. Thank you so much.

Regards,
Tanvi Murke

**Comment by biblicabeebli** [comment] 2023-08-08 19:08
(My active work right now is on Android, adding new features that have been in development on iOS. I'm trying to get onto the app store as soon as possible, I'll include any fixes or changes discovered here if we can get them up.  Bulk of the work on the feature ended yesterday, that feature has no overlap with this reported bug.)

I need the following from you:
- _I need that exported study settings json. The rest of this is immaterial until I have that._
- Are participants in you study using the app version downloadable from the link on the website, or are they using the version of the app in the Play store? The Play store app will auto update (based on the user's personal settings), but the download link version will not. 
- The most up-to-date app version is 3.4.2. I need you to confirm that this is the version running on affected users.  This information is present on the participant page provided your server is up-to-date.
- On the participant dashboard (the table with statistics in it) it may be very helpful to get a sense of what data streams are/are not working. Get in touch out-of-band if you would like to do a call and a screen share, or you can take a screenshot.
- Question: are you set up with push notification credentials on the backend server? Have you tested to confirm that they work? (I would have had to already provide you with push notification credentials out-of-band. I don't think this has happened.)
- Question: are your participants reporting that the permanent notification is visible in their notifications menu? or is that missing.
- To the best approximation, when did this issue start?

**Comment by biblicabeebli** [comment] 2023-08-08 19:27
(Updated the title of the issue so it's a little easier to track in our bug/issue tracker table.)

If you can take a screenshot of an affected participant page device info setting (or two or three) that will also help.

**Comment by biblicabeebli** [comment] 2023-08-08 19:29
> Thank you so much for reverting back.
Slightly lost, what was this comment with respect to? (or maybe it has become irrelevant?)

**Comment by tanvimurke** [comment] 2023-08-09 18:47
Hi Eli,

I have attached one JSON file for your reference. Also, will it be possible
for us to arrange a short call to discuss the issue so you can get a clear
understanding?
Looking forward to hearing from you soon.

Regards,
Tanvi Murke

**Comment by biblicabeebli** [comment] 2023-08-09 18:51
It looks like you are responding via the email interface to a github issue, the attachment was not forwarded. You will need to email me directly or go to the issue page. (issue 66)

**Comment by tanvimurke** [comment] 2023-08-10 17:08
Hi Eli, 

I am not able to attach the JSON file via Github. Could you please share your email id so I can send it to you there?

Regards,
Tanvi Murke

**Comment by biblicabeebli** [comment] 2023-08-11 00:24
it is my username at gmail dot com

**Comment by biblicabeebli** [comment] 2023-08-22 07:50
I have reviewed data about participant data collection with respect to our own production servers and studies, and I've looked at your study configuration and found nothing unusual.  It is not a common issue on the most recent version of the android app for participants who should have uploaded GPS data to have failed to.

Sometimes there are participants that do not allow location data permissions, this is the most likely cause here.

I asked for six additional data points and cannot continue without them.

**Comment by biblicabeebli** [comment] 2023-08-22 20:04
I've done some more reviewing, turns out there is more of this going on than I first thought, but I do need to compare to other data streams to make a better determination.

**Comment by tanvimurke** [comment] 2023-08-23 02:37
Hi Eli,

Thank you so much for the update.
Adding @Sagar Baviskar ***@***.***>

Regards,
Tanvi Murke

**Comment by biblicabeebli** [comment] 2023-08-29 10:30
@hydawo note the above comment, get ready to notify active studies.

**Comment by biblicabeebli** [comment] 2023-08-30 19:22
Ok, 3.5.1 is pushed.

It can take a day (usually just a few hours though) for the Play store update to roll out, but the version available at the link on Beiwe website pages now downloads 3.5.1.  You may need to force-refresh the page to get it working.

Updates are Mostly lmited to the permissions fix, there's some Unavoidable Android 13 Compatibility Stuff included. (Hopefully that doesn't somehow screw us.)

**Comment by biblicabeebli** [comment] 2023-09-01 16:11
Current play store status is
> You've submitted an update to your app. We'll update this page when we've finished the review. Reviews typically take up to 7 days. For more information, go to Publishing overview.

But the item in review is 
> App must target Android 13 (API level 33) or higher

Which... we do. The update is that, the 2 permissions fixes that that update required, and the bug fix from this thread.

Whatever. I will try and update this thread when its finally out, but I will die on the hill of this making no sense.

**Comment by biblicabeebli** [comment] 2023-09-02 23:31
Ok it's FINALLY out on the app store.  🙄

**Comment by hydawo** [comment] 2023-09-07 20:08
Closing this issue. Thread is not locked, will continue to respond if anything comes up on this thread.

**Comment by biblicabeebli** [comment] 2023-09-09 06:25
Was interrupted an investigation where I was struggling to generate gps data after patching the data bug caused by locale number formatting.

(which is included in 3.5.2a)

Also, @tanvimurke stated the have patches regarding android 13. @tanvimurke , are those on a fork on github? or just local changes. I did my own patching but I missed something bad enough to hard-crash one of the two high-level feature builds outside of testing conditions. (The crash doesn't occur when deploying to the device from the dev environment, or when downloading from the app store. It only triggers when you build an apk, stick the file on the device, and install from there.)

**Comment by biblicabeebli** [comment] 2023-09-12 18:32
I have now confirmed that the issue I was seeing was not related to normal operations, it was purely a local bug. GPS definitely records data.

**Closed** 2023-09-12 18:33 UTC
Labels: bug
