### ISSUE TITLE
Inconsistent Android data collection

### ISSUE THREAD

**Issue by writezhe** [onnela-lab/beiwe-android#27] opened 2018-04-20 15:33 UTC
We've run into issues collecting Android consistently in our internal pilot, and several phones are missing >24 hours of data. This may be related to #19. I apologize in advance for the inability to identify the cause of this issue.

_Settings:_
We've installed Beiwe 2.2.5 from the Play Store on 10 Android phones (this may be related to #19). I'm using AMI v0.1. 
We're only collecting GPS data with 60/660 sec on/off. Data upload is every hour, and not allowed over cellular. We set the "duration before auto-logout" to ~100 days. 
We only tested an initial survey and one text survey (no audio survey in this pilot).

_Evidence:_
![image](https://user-images.githubusercontent.com/591893/39058704-97b1bda4-448a-11e8-9df6-9813f14bd403.png)
![image](https://user-images.githubusercontent.com/591893/39058786-c9716e3e-448a-11e8-9b83-ea5450605c54.png)
![image](https://user-images.githubusercontent.com/591893/39059034-775305c6-448b-11e8-8209-1bb2671a9db9.png)
Here are three histograms of the Android applog. The height marks the number of lines in the log. In my understanding, this should be approximately constant if the Beiwe background service is alive, or at least some lines per hour. 

Instead, for almost all phones, there are significant gaps in time (including entire days having no applog entries). The first two images are relatively good: the first is missing Sunday + Monday and half of Thursday/Friday; the second stopped sending data on Monday and I downloaded the data on Friday (not a chunking issue, there is no raw data). The third phone has been installed longer and is even more spotty. Some other phones sent data for a couple days and then stopped; even with a force restart it only sent data for a couple hours. 
(Two of the phones are Chinese manufacturers, which may be causing some problems, though we don't expect Chinese phones in the actual study.)
(I can attach a zip file with anonymous data and the actual logs for the phones.) 

```
Phone models:
Samsung Galaxy S7 (SM-G935F) (Mar 2016) (Android 7)
LGE Tribute Dynasty (LG-SP200) (2017/2018?) (Android 7.1.2)
LGE G5 (LG-H830) (April 2016) (Android 7.0)
Samsung Galaxy J3 (SM-J320V) (June 2016) (Android 6.0.1)
Samsung Galaxy Note 5 (SM-N920G) (June 2016) (Android 7.0)
Xiaomi Redmi Note 4 (Jan 2017) (Android 7.0)
Samsung Galaxy S9 (SM-G960U) (Feb 2018) (Android 8.0)
Vivo Vivo X7Plus (June 2016) (Android 5.1.1)
```
_Hypotheses:_
I don't think this is a server issue because the 10+ iOS testers all have applog data almost consistently for 24 hours (except when some force-killed the app).

With my Android developer, we think it could be two things: the BackgroundService restart (which is scheduled to try to restart every 10 seconds) is not happening, or the data is being stuck on the phone and not being uploaded. There is some evidence of the latter, with some Androids uploading many files at once to S3, though I don't think so because even between uploads, there are a lot of gaps in the applog, which would not be there if it was just a data upload issue. Another idea is that it could be a RAM issue on the phone killing the Service, but the issue seems consistent with newer phones (e.g. Galaxy S9).

I've also asked people to avoid force-killing the app, turning off wifi, and to turn all the permissions on.

_Next steps:_
I will run another pilot focused on Android phones, using AMI v0.2 and allowing data upload over cellular too. I will try to install the debug version on a few phones to get more information too.

I'm sorry this issue is vague, we're having a bunch of trouble re-creating and identifying the problem, partly because the problem takes time to occur and we didn't have access to rooted phones.
I wanted to raise the issue to see if there is some advice in how to debug this? Suggestions for symptoms to look for, debug options, or how to re-create the problem? We'd like to get a better sense for the rate of failure, and if there are options on the user side to re-enable data collection.
Thanks!

**Comment by writezhe** [comment] 2018-04-24 12:49
Addendum: we're trying an AlarmManager piece of code as an alternative way to re-awaken the background service if the service is gone. It will take us a little while to evaluate this, since we need to get some Androids and the issue can take several days to appear. I wanted to share this snippet though in case you think that this code won't work or you've already tried it and we're going down the wrong track. Thanks!

```
Intent restartServiceIntent = new Intent( getApplicationContext(), BackgroundService.class);
        restartServiceIntent.setPackage( getPackageName() );
        PendingIntent restartServicePendingIntent = PendingIntent.getService(getApplicationContext(), 1, restartServiceIntent, 0 );
        AlarmManager alarmService = (AlarmManager) getApplicationContext().getSystemService( Context.ALARM_SERVICE );
        alarmService.setRepeating(AlarmManager.RTC_WAKEUP, System.currentTimeMillis() + 1000 * 60 * 2, 100 * 60 * 2, restartServicePendingIntent);
```

**Comment by writezhe** [comment] 2018-04-30 14:38
I've only been able to get this on 3 Android phones, but the AlarmManager seems to have made a marked improvement in the background service's uptime consistency. The app logs are now reporting mostly constant lines per hour, noting GPS on/off changes. Comparing the same phones from before and after the code change, there seems to be a notable difference in the reduction of missing periods. 
However, one of the phones did still seems to quit the service and not be able to restart. I'm not sure if this is idiosyncratic to the phone, but there do still seem to be problems present.

Do you think something like this snippet would be a viable addition? Or do you have suggestions for tweaks to it?
I'm going to stop testing this AlarmManager code and instead try to get 2-3 phones to install the 2.2.7 beta version with the Sentry logging.

**Comment by zagorsky** [comment] 2018-05-24 03:59
Hi @writezhe, we've implemented a recurring restart timer as you suggested, and we've also made a bunch of other fixes to the Android app.  The newest version of the Beiwe Android app is 2.4.0, and it's available from the Google Play Store if you enroll as a beta tester.

It would be helpful to us if you could install 2.4.0 and see if it fixes the issues you were seeing with unreliable data!

**Comment by usanchez** [comment] 2018-06-22 15:28
Is this related to issue #10 ? Any workarounds to solve this?

**Comment by sesterki** [comment] 2018-06-25 21:49
What version of the code base are you running?

**Comment by usanchez** [comment] 2018-06-26 10:17
Up-to-date with the latest commit ([63b62339327a249ec765b6a090b34602ab31ba78](https://github.com/onnela-lab/beiwe-android/commit/63b62339327a249ec765b6a090b34602ab31ba78)). 
Loss of GPS and ACC data minutes after completing a survey. Sometimes, if a start another survey, the GPS & ACC data is gathered again for a short amount of time, and then, again, GPS & ACC data loss. I am not able to reproduce this second escenario consistently, but otherwise, the GPS & ACC data loss is consistent.

**Comment by mariasimoneau** [comment] 2018-06-26 21:11
Thanks for the information @usanchez.  Are you running the Beiwe2 app from the google play store or your own version of the app?  I'd be curious to hear what kind of phone and what OS & version you're running on the phone.  We've started a FAQ for troubleshooting which may give you some ideas about your problem.  http://wiki.beiwe.org/wiki/Beiwe_Troubleshooting.   Typical problems are GPS must be turned on & Beiwe must have access to it . When the Beiwe app is installed, you must specify that battery conservation is OFF for Beiwe.  Battery saving modes disable Beiwe so no data is collected which sounds like what you're experiencing.  This can be fixed in settings>battery>app power monitor - remove Beiwe so that it is an "unmonitored app" so it can run when needed to collect data.

**Comment by biblicabeebli** [comment] 2022-11-18 20:51
In general it was found that data was "okay", among other confounding issue has been the spread of android os versions changing the way they interact with power saving.

This is an open, ongoing issue, we are allocating time to fundamentally improve internal timer consistency within the android app writ large.

Fundamentally, the api we use ("alarms") makes unreliable guarantees - and those guarantees differ depending on android version AND the sensor's power draw AND the class of sensor in use (AND though I can't confirm this, there is *always* manufacturer background radiation junk that confuses this).

Behavior was substantially improved by shifting to a ForegroundService a while (year+) ago, but I believe that when the play store shifted to requiring a Target SDK version of android 11 it caused android versions  7-10 to experience reduced data collection.  (Android 6 and earlier were probably unaffected but obviously we don't care about that anymore.)

I've deleted a few distracting comments from the thread, thank you @writezhe, I know this has been silent for a while but your insights here are/were actually quite helpful.

The play store just (nov 2022) updated SDK target requirements to target Android 12, which has substantially changed power saving mode interactions, so any release to the app store is going to be delayed until those are resolved.  There is a new permission that may help/harm us, which is a set-exact-alarms.  I will also be experimenting with other apis and tactics.

(grr-arg, notifications have changed again....)

**Comment by biblicabeebli** [comment] 2023-04-19 22:22
Many Many improvements have been made on this issue, which was posted 5 years ago.  I am closing this as I no longer consider the data collected by the android app to be so critically poor.

**Closed by biblicabeebli** 2023-04-19 22:22 UTC
